name: Tests

on:
  - push

defaults:
  run:
    shell: bash -l {0}

jobs:

  build_linux:
    name: "linux Tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Setup Python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      # run setup.py
      - name: Setup.py
        run: python3 setup.py install --user

      # run test-CRNS
      - name: test-CRNS
        run: python3 test_CRNS.py

  build_windows:
    name: "Windows Tests"
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Setup Python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      # run setup.py
      - name: Setup.py
        run: python3 setup.py install --user

      # run test-CRNS
      - name: test-CRNS
        run: python3 test_CRNS.py


  build_mac:
    name: "Mac Tests"
    runs-on: "macos-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Setup Python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: install pycddlib
        run: pip3 install pycddlib
      # run setup.py
      - name: Setup.py
        run: python3 setup.py install --user

      # run test-CRNS
      - name: test-CRNS
        run: python3 test_CRNS.py
