name: Continuous Delivery

on:
  - push

defaults:
  run:
    shell: bash -l {0}

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Setup Python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # run setup.py
      - name: Setup.py
        run: python3 setup.py install --user

      - name: Read rn_test.txt
        id: ReactionNetwork
        uses: juliangruber/read-file-action@v1
        with:
          path: ./networks/rn_test.txt
      - name: Echo test network
        run: echo "${{ steps.ReactionNetwork.outputs.content }}"

      # run test-file
      - name: test-file
        run: python3 test_CRNS.py